#!/usr/bin/env pwsh
#
# PowerShell Profile Updater
#
# Updates profile files and tools to latest versions
#

param(
    [string]$RepoOwner,
    [string]$RepoName,
    [string]$Branch
)

function Get-RepoBase {
    param(
        [Parameter(Mandatory)][string]$RepoOwner,
        [Parameter(Mandatory)][string]$RepoName,
        [Parameter(Mandatory)][string]$Branch
    )

    $Ref = $Branch.Trim('/')
    if ($Ref -like '*/*' -and -not $Ref.StartsWith('refs/')) { $Ref = "refs/heads/$Ref" }
    "https://raw.githubusercontent.com/$RepoOwner/$RepoName/$Ref"
}

function New-RepoConfigContent {
    param(
        [Parameter(Mandatory)][string]$RepoOwner,
        [Parameter(Mandatory)][string]$RepoName,
        [Parameter(Mandatory)][string]$Branch,
        [Parameter(Mandatory)][string]$GitPromptStyle
    )

    $RepoBase = Get-RepoBase -RepoOwner $RepoOwner -RepoName $RepoName -Branch $Branch

    $EscapedOwner = ('' + $RepoOwner) -replace "'", "''"
    $EscapedName = ('' + $RepoName) -replace "'", "''"
    $EscapedBranch = ('' + $Branch) -replace "'", "''"
    $EscapedRepoBase = ('' + $RepoBase) -replace "'", "''"
    $EscapedGitPromptStyle = ('' + $GitPromptStyle) -replace "'", "''"

    @"
# Auto-generated by ps-profile installer
[PSCustomObject]@{
    Owner = '$EscapedOwner'
    Name = '$EscapedName'
    Branch = '$EscapedBranch'
    Base = '$EscapedRepoBase'
    GitPromptStyle = '$EscapedGitPromptStyle'
}
"@
}

# Load persisted repo config if present (install.ps1 writes it)
$RepoConfigPaths = @(
    (Join-Path $HOME 'Documents\PowerShell\ps-profile.repo.ps1'),
    (Join-Path $HOME 'Documents\WindowsPowerShell\ps-profile.repo.ps1')
)
$ExistingRepoConfigPaths = $RepoConfigPaths | Where-Object { Test-Path $PSItem }
$ExistingConfigPath = $ExistingRepoConfigPaths | Select-Object -First 1
$PersistedRepoConfig = $Null
if ($ExistingConfigPath) {
    try {
        $PersistedRepoConfig = . $ExistingConfigPath
    } catch {
        Write-Warning "Failed to load repo config from '$ExistingConfigPath': $($PSItem.Exception.Message)"
    }
}

# Use params > config > upstream defaults
if ([string]::IsNullOrWhiteSpace($RepoOwner)) { $RepoOwner = if ($PersistedRepoConfig -and $PersistedRepoConfig.Owner) { $PersistedRepoConfig.Owner } else { 's-weigand' } }
if ([string]::IsNullOrWhiteSpace($RepoName)) { $RepoName = if ($PersistedRepoConfig -and $PersistedRepoConfig.Name) { $PersistedRepoConfig.Name } else { 'ps-profile' } }
if ([string]::IsNullOrWhiteSpace($Branch)) { $Branch = if ($PersistedRepoConfig -and $PersistedRepoConfig.Branch) { $PersistedRepoConfig.Branch } else { 'main' } }

$RepoBase = Get-RepoBase -RepoOwner $RepoOwner -RepoName $RepoName -Branch $Branch

Write-Host "Updating PowerShell Profile..." -ForegroundColor Cyan
Write-Host "  Repo:   https://github.com/$RepoOwner/$RepoName" -ForegroundColor Gray
Write-Host "  Branch: $Branch" -ForegroundColor Gray

$TempDir = Join-Path $Env:TEMP 'ps-profile-update'

# Create temporary directory
if (Test-Path $TempDir) {
    Remove-Item $TempDir -Recurse -Force
}
New-Item -ItemType Directory -Path $TempDir -Force | Out-Null

# Download latest profile files
Write-Host "Downloading latest profile files..." -ForegroundColor Yellow
$GitPromptStyle = if ($PersistedRepoConfig -and $PersistedRepoConfig.GitPromptStyle) { $PersistedRepoConfig.GitPromptStyle } else { 'full' }

$FilesToDownload = @{
    'profile.ps1' = "$RepoBase/profile.ps1"
    'aliases.ps1' = "$RepoBase/aliases.ps1"
    'themes/ohmy-posh.omp.json' = "$RepoBase/themes/ohmy-posh.omp.json"
}

foreach ($File in $FilesToDownload.GetEnumerator()) {
    $LocalPath = Join-Path $TempDir $File.Key
    $LocalDir = Split-Path $LocalPath -Parent

    if (-not (Test-Path $LocalDir)) {
        New-Item -ItemType Directory -Path $LocalDir -Force | Out-Null
    }

    Invoke-RestMethod $File.Value -OutFile $LocalPath
    Write-Host "  ✓ $($File.Key)" -ForegroundColor Green
}

# Download fast theme if user prefers it (optional — may not exist on upstream)
if ($GitPromptStyle -eq 'fast') {
    $FastThemePath = Join-Path $TempDir 'themes/ohmy-posh-fast.omp.json'
    try {
        Invoke-RestMethod "$RepoBase/themes/ohmy-posh-fast.omp.json" -OutFile $FastThemePath
        Write-Host "  ✓ themes/ohmy-posh-fast.omp.json" -ForegroundColor Green
    } catch {
        # Fast theme not available on this branch — fall back to full and persist the change
        Write-Host "  ⚠ Fast theme not available, falling back to full" -ForegroundColor Yellow
        $GitPromptStyle = 'full'

        $RepoConfigContent = New-RepoConfigContent -RepoOwner $RepoOwner -RepoName $RepoName -Branch $Branch -GitPromptStyle $GitPromptStyle
        foreach ($ConfigPath in $RepoConfigPaths) {
            try {
                $ConfigDir = Split-Path -Path $ConfigPath -Parent
                if (-not (Test-Path $ConfigDir)) {
                    New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null
                }
                $RepoConfigContent | Set-Content -Path $ConfigPath -Encoding utf8 -Force
            } catch {
                Write-Warning "Failed to update git prompt style in '$ConfigPath': $($PSItem.Exception.Message)"
            }
        }
    }
}

# Update PowerShell modules
Write-Host "Updating PowerShell modules..." -ForegroundColor Yellow
$Modules = @('PSReadLine', 'Terminal-Icons')
foreach ($Module in $Modules) {
    Update-Module -Name $Module -Force
    Write-Host "  ✓ $Module" -ForegroundColor Green
}

# Update external tools
Write-Host "Updating external tools..." -ForegroundColor Yellow
$Tools = @(
    'JanDeDobbeleer.OhMyPosh',
    'ajeetdsouza.zoxide',
    'BurntSushi.ripgrep.MSVC',
    'sharkdp.bat',
    'sharkdp.fd',
    'Schniz.fnm',
    'Dystroy.broot'
)
foreach ($Tool in $Tools) {
    winget upgrade $Tool --silent --accept-package-agreements
    Write-Host "  ✓ $Tool" -ForegroundColor Green
}

# Update profile files
Write-Host "Updating profile files..." -ForegroundColor Yellow

# PowerShell 7+
$PS7ProfileDir = "$HOME\Documents\PowerShell"
Copy-Item (Join-Path $TempDir 'profile.ps1') "$PS7ProfileDir\profile.ps1" -Force
Copy-Item (Join-Path $TempDir 'aliases.ps1') "$PS7ProfileDir\aliases.ps1" -Force

# Windows PowerShell 5.x
$PS5ProfileDir = "$HOME\Documents\WindowsPowerShell"
Copy-Item (Join-Path $TempDir 'profile.ps1') "$PS5ProfileDir\profile.ps1" -Force
Copy-Item (Join-Path $TempDir 'aliases.ps1') "$PS5ProfileDir\aliases.ps1" -Force

# Update theme (respects git prompt style preference from install)
$ThemeSource = if ($GitPromptStyle -eq 'fast') { 'themes/ohmy-posh-fast.omp.json' } else { 'themes/ohmy-posh.omp.json' }
$ThemesDir = Join-Path $HOME 'themes'
if (-not (Test-Path $ThemesDir)) {
    New-Item -ItemType Directory -Path $ThemesDir -Force | Out-Null
}
Copy-Item (Join-Path $TempDir $ThemeSource) (Join-Path $ThemesDir 'ohmy-posh.omp.json') -Force

Write-Host "  ✓ Profile files updated" -ForegroundColor Green

# Regenerate completions
Write-Host "Regenerating completions..." -ForegroundColor Yellow
if (Get-Command rg -ErrorAction SilentlyContinue) {
    # Create completions directories if they don't exist
    $PS7CompletionsDir = "$PS7ProfileDir\completions"
    $PS5CompletionsDir = "$PS5ProfileDir\completions"
    if (-not (Test-Path $PS7CompletionsDir)) {
        New-Item -ItemType Directory -Path $PS7CompletionsDir -Force | Out-Null
    }
    if (-not (Test-Path $PS5CompletionsDir)) {
        New-Item -ItemType Directory -Path $PS5CompletionsDir -Force | Out-Null
    }

    # Generate completions directly to profile directories
    rg --generate complete-powershell | Out-File "$PS7CompletionsDir\_rg.ps1" -Encoding utf8
    rg --generate complete-powershell | Out-File "$PS5CompletionsDir\_rg.ps1" -Encoding utf8
    Write-Host "  ✓ Ripgrep completions" -ForegroundColor Green
}

# Configure Windows Terminal keybindings
Write-Host "Configuring Windows Terminal keybindings..." -ForegroundColor Yellow
$TerminalSettingsPath = "$Env:LOCALAPPDATA\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json"
if (Test-Path $TerminalSettingsPath) {
    try {
        $TerminalSettings = Get-Content $TerminalSettingsPath -Raw | ConvertFrom-Json

        # Disable Alt+Enter keybinding if not already disabled
        if (-not $TerminalSettings.actions) {
            $TerminalSettings | Add-Member -MemberType NoteProperty -Name 'actions' -Value @() -Force
        }

        # Check if Alt+Enter is already unbound
        $AltEnterUnbound = $TerminalSettings.actions | Where-Object {
            $PSItem.keys -eq 'alt+enter' -and $Null -eq $PSItem.command
        }

        if (-not $AltEnterUnbound) {
            # Convert to array if not already
            if ($TerminalSettings.actions -isnot [System.Array]) {
                $TerminalSettings.actions = @($TerminalSettings.actions)
            }

            # Add the unbound keybinding
            $TerminalSettings.actions = @($TerminalSettings.actions) + @([PSCustomObject]@{
                command = $Null
                keys    = 'alt+enter'
            })

            # Save settings with proper formatting and depth
            $TerminalSettings | ConvertTo-Json -Depth 10 | Set-Content $TerminalSettingsPath -Encoding utf8
            Write-Host "  ✓ Windows Terminal Alt+Enter keybinding disabled" -ForegroundColor Green
        } else {
            Write-Host "  ✓ Windows Terminal Alt+Enter keybinding already disabled" -ForegroundColor Gray
        }
    } catch {
        Write-Host "  ✗ Failed to configure Windows Terminal keybindings: $PSItem" -ForegroundColor Red
    }
} else {
    Write-Host "  ✓ Windows Terminal settings not found" -ForegroundColor Gray
}

# Clean up
Remove-Item $TempDir -Recurse -Force

Write-Host "`n✅ Update complete!" -ForegroundColor Green
Write-Host "Restart PowerShell to activate the updated profile." -ForegroundColor Cyan
